celo api
0xProject/0x-api pull request #784
Opened 2021-11-04 16:47 UTC by dextracker

# Description

# Testing Instructions

# Checklist

-   [ ] Update [documentation](https://github.com/0xProject/website/blob/development/mdx/api/index.mdx) as needed. **Website Documentation PR:**
-   [ ] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.
-   [ ] Test changes on the staging environment with [Matcha API Staging](https://api-staging.matcha.xyz).

    -   [ ] SRA/Limit orders
    -   [ ] Swap endpoints
    -   [ ] Meta transaction endpoints
    -   [ ] Depth charts

    For more information see `0x API Matcha smoke test runbook` in Quip.

2021-11-17 05:19 UTC, dekz requested changes

2021-11-17 05:19 UTC, dekz commented on .env_example
> -# Required
We keep this for documenting the ENV vars for others

2021-11-17 05:19 UTC, dekz commented on hardhat.config.js
> +require("@nomiclabs/hardhat-waffle");
Not needed to be checked in, perhaps look at a `.gitignore` for this file if you want to keep it around locally

2021-11-17 05:19 UTC, dekz commented on package.json
> +        "@nomiclabs/hardhat-waffle": "^2.0.1",
```suggestion

```

2021-11-17 05:19 UTC, dekz commented on package.json
> +        "ethereum-waffle": "^3.2.0",
```suggestion
```

2021-11-17 05:19 UTC, dekz commented on src/services/swap_service.ts
> +        const CELO_CHAIN_ID = 42220;
```suggestion

```

Should be able to use `ChainId.Celo` instead

2021-11-17 05:19 UTC, dekz commented on src/services/swap_service.ts
> +            case CELO_CHAIN_ID:
```suggestion
            case ChainId.Celo:
```

2021-11-17 05:19 UTC, dekz commented on src/services/swap_service.ts
> +                    buyTokenAddress: isETHBuy ? '0x471ece3750da237f93b8e339c536989b8978a438' : buyToken,
For a fresh reader they'd have no idea why this is duplicated with only some (2?) lines of difference. Leave a comment for future self why this is needed.

It's probably cleaner to have a helper function which takes the chain and returns the Native token address

Something like


```typescript
function nativeAssetForChain(chainId: ChainId): string => {
    switch (chainId) {
        case ChainId.Celo:
            return '0x471ece3750da237f93b8e339c536989b8978a438';
        default:
            return ETH_TOKEN_ADDRESS;
    }
}
```

2021-11-17 10:12 UTC, kimpers commented on src/services/swap_service.ts
> -        const { gasPrice, sourceBreakdown, quoteReport, extendedQuoteReportSources, priceComparisonsReport } =
Is it intentional to remove `extendedQuoteReportSources`?

2021-11-20 00:32 UTC, dorothy-zbornak commented on src/services/swap_service.ts
> -            sellTokenAddress: isETHSell ? ETH_TOKEN_ADDRESS : sellToken,
I think we want the old behavior?

2021-11-29 20:32 UTC, dorothy-zbornak approved these changes

2021-11-29 20:36 UTC, merged